### ISSUE TITLE
"relation-type-id": "IsCitedBy",

### ISSUE THREAD

**Issue by dwief-usgs** [usgs-biolab/publink#12]
Alter relationship type from "IsReferencedBy" to the equivalent "IsCitedBy".  Apparently "IsReferencedBy" may be dropped in future

- [x]  change "relation-type-id": "IsReferencedBy"   to  "relation-type-id": "IsCitedBy"   
         see line 181 ->  in to_related_identifiers() function

- [x] search and change this notation in rest of code (verify no other occurrences)

- [x] search and change this notation in readme and documention

**Comment by dwief-usgs** [comment]
@mlangseth can you verify I captured this correctly

**Comment by mlangseth** [comment]
@dwief-usgs that looks correct. Thanks!

**Comment by dwief-usgs** [comment]
see https://github.com/usgs-biolab/publink/pull/13
