### ISSUE TITLE
Clarify programming language/software needed to use in website and/or README

### ISSUE THREAD

**Issue by TrashBirdEcology** [usgs-biolab/publink#4]
Reading through the package title ("Methods to help build relationships between data and the publications they are referenced in."), and Purpose and Requirements sections in [the .io](https://publink.readthedocs.io/en/latest/readme.html), it is not clear that this is to be run using python. Also, the word 'python' does not appear at all on the [readme.html](https://publink.readthedocs.io/en/latest/readme.html).

**Comment by dwief-usgs** [comment]
Python is now referenced in the package title and readme
